# Generated by Django 4.2.11 on 2024-04-29 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blueprint', '0004_learningobjective'),
        ('items', '0004_item_enemy_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='learning_objective',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='blueprint.learningobjective'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='items.question'),
        ),
    ]
