# Generated by Django 4.2.11 on 2024-04-29 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blueprint', '0006_learningobjective_reference'),
        ('items', '0008_remove_item_is_active_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='learning_objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blueprint.learningobjective'),
        ),
        migrations.AlterField(
            model_name='item',
            name='stem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='items.question'),
        ),
    ]
