# Generated by Django 4.2.11 on 2024-04-29 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_item_created_by_alter_item_learning_objective_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='created_by',
            new_name='author',
        ),
    ]
