# Generated by Django 4.2.11 on 2024-04-30 13:25

from django.db import migrations, models
import ams.apps.items.validators


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_rename_created_by_item_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='estimated_p_value',
            field=models.FloatField(default=0.85, help_text='Enter a value between 0 and 1', validators=[ams.apps.items.validators.validate_p_value]),
        ),
        migrations.AddField(
            model_name='item',
            name='p_value',
            field=models.FloatField(blank=True, null=True, validators=[ams.apps.items.validators.validate_p_value]),
        ),
    ]
