# Generated by Django 4.2.11 on 2024-05-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_item_estimated_p_value_item_p_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='legacy_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
