# Generated by Django 4.2.11 on 2024-04-29 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprint', '0004_learningobjective'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='items_per_form',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
