# Generated by Django 4.2.11 on 2024-04-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprint', '0005_subcategory_items_per_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningobjective',
            name='reference',
            field=models.CharField(default='1.1.1', help_text='e.g., 1.1.1', max_length=8),
            preserve_default=False,
        ),
    ]
