# Generated by Django 4.2.11 on 2024-04-29 00:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rationale', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
