# Generated by Django 4.2.11 on 2024-04-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='enemy_items',
            field=models.ManyToManyField(blank=True, to='items.item'),
        ),
    ]
