# Generated by Django 4.2.11 on 2024-04-29 01:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blueprint', '0003_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.CharField(max_length=255)),
                ('bloom_level', models.IntegerField(choices=[(1, 'Remember'), (2, 'Understand'), (3, 'Apply'), (4, 'Analyze'), (5, 'Evaluate'), (6, 'Create')])),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blueprint.subcategory')),
            ],
            options={
                'verbose_name': 'Learning Objective',
                'verbose_name_plural': 'Learning Objectives',
            },
        ),
    ]
